settings:
  rule: "-"
  ruleRepetition: 3
  ruleSpaces: false

  bullet: "-"

plugins:
  - remark-parse
  - - remark-frontmatter
    - type: yaml
      marker: "-"
  - - remark-gfm
    - tablePipeAlign: false
  - remark-lint
  - - ./tools/docs/src/remark-frontmatter-ajv2020.cjs
    - strict: true
      yaml.schemas:
        docs/shared/schemas/rulebook-frontmatter.schema.yaml:
          - docs/ja/handbook/rulebooks/**/*.md
        docs/shared/schemas/guide-frontmatter.schema.yaml:
          - docs/ja/handbook/guidelines/**/*.md
        docs/shared/schemas/instruction-frontmatter.schema.yaml:
          - docs/ja/handbook/instructions/**/*.md
        docs/shared/schemas/deliverable-frontmatter.schema.yaml:
          - docs/ja/product/**/*.md
          - docs/ja/projects/**/*.md
          - docs/ja/handbook/samples/**/*.md
