settings:
  rule: "-"
  ruleRepetition: 3
  ruleSpaces: false

  bullet: "-"

plugins:
  - remark-parse
  - - remark-frontmatter
    - type: yaml
      marker: "-"
  - - remark-gfm
    - tablePipeAlign: false
  - remark-lint
  - - ./tools/docs/src/remark-frontmatter-ajv2020.cjs
    - strict: true
      yaml.schemas:
        docs/specdojo/schemas/v1/rulebook-frontmatter.schema.yaml:
          - docs/ja/specdojo/rulebooks/**/*.md
        docs/specdojo/schemas/v1/guide-frontmatter.schema.yaml:
          - docs/ja/specdojo/guidelines/**/*.md
        docs/specdojo/schemas/v1/standard-frontmatter.schema.yaml:
          - docs/ja/specdojo/standards/**/*.md
        docs/specdojo/schemas/v1/instruction-frontmatter.schema.yaml:
          - docs/ja/specdojo/instructions/**/*.md
        docs/specdojo/schemas/v1/deliverable-frontmatter.schema.yaml:
          - docs/ja/product/**/*.md
          - docs/ja/projects/**/*.md
          - docs/ja/specdojo/samples/**/*.md
