settings:
  rule: "-"
  ruleRepetition: 3
  ruleSpaces: false

  bullet: "-"

plugins:
  - remark-parse
  - - remark-frontmatter
    - type: yaml
      marker: "-"
  - - remark-gfm
    - tablePipeAlign: false
  - remark-lint
  - - ./tools/docs/src/remark-frontmatter-ajv2020.cjs
    - strict: true
