extends: default

rules:
  indentation:
    spaces: 2
    indent-sequences: true
  document-start:
    present: false
  line-length:
    max: 120
    level: warning
    allow-non-breakable-words: true
  trailing-spaces: enable
  key-duplicates: enable
  truthy:
    allowed-values: ["true", "false", "on", "off", "yes", "no"]
  empty-lines:
    max: 2
  comments:
    min-spaces-from-content: 1
